import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  kbSidebar: [
    {
      type: 'autogenerated',
      dirName: 'knowledge-base',
    },
  ],
  projectsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'projects',
    },
  ],
};

export default sidebars;
